dist: bionic
language: python
sudo: required
addons:
  hosts:
    - lh
  sauce_connect:
    tunnel_domains: lh
  chrome: stable
env:
  global:
  - secure: EVObCafLubboW7PQ69OhLI9qSMWDUYuL8EvXCX2MsBzlgX1W6cc62IJbKV87EHOnu/2KgHXYNVYN4rmydVbOU+nMHwtryf8+utNcyuDp40kKoNjWhWue++AheXgAjUt1lON4/kiZ5gxEupQeEXDPvP/5LrUuDUEQRwJa6pbivD8=
  - secure: KOpU31rbmwrjGovRX769F9H1/+KdtB5KJfMKIMRZPTeaH/zrlUDaTh9lBOkAFD1S/0nagsrXIUq9e9PJD3pEWze09VUK0mivCl96/ZXFt605UJXSKgWvZNJdRLexzwPhHd/MDzbMqTfrAlN6x9OSA5uIOaGzaQSZjkXjed8IkRk=
  - secure: MWsPYunBeYxPHk5zngCHe6K67FQc6Da9EL17vd2dLEOqePD3VPI+wVdfUDzwkdc7pslM3/JNUroMtCiVkLi7TBNH37hZ5TN1/lG/5kyqobMkm8xLInrrUOhSgvL566nRBb5QMsIMO4+yg7tQHR0EwHHjAOaI0Yw/2F2WgEZN3TU=
#Tokens order: sauce_username, sauce_token, codacy_project_token
matrix:
  fast_finish: true
  include:
    - env: GLTEST='test' CODACY=true
    - env: GLTEST='build_and_install' DISTRIBUTION='buster'
    - env: GLTEST='build_and_install' DISTRIBUTION='focal'
    - env: GLTEST='end2end-0' BROWSER='chrome latest'
    - env: GLTEST='end2end-1' BROWSER='firefox latest'
    - env: GLTEST='end2end-2' BROWSER='edge latest'
    - env: GLTEST='end2end-3' BROWSER='ie 11'
    - env: GLTEST='end2end-4' BROWSER='android 10'
  allow_failures:
    - env: GLTEST='end2end-0' BROWSER='chrome latest'
    - env: GLTEST='end2end-1' BROWSER='firefox latest'
    - env: GLTEST='end2end-2' BROWSER='edge latest'
    - env: GLTEST='end2end-3' BROWSER='ie 11'
    - env: GLTEST='end2end-4' BROWSER='android 10'
before_install:
  - nvm install stable
  - nvm use stable
install: true
script:
  - $TRAVIS_BUILD_DIR/travis/script.sh
