language: python
dist: trusty
sudo: required
env:
  global:
    - secure: Fd+dALSXhRgP44UaiED0xbJMHLxzON1Vcu6ufxDGgyl9NYepT0cfMGczLocfawc35ig++SyfytfpaPRhy3yG7WhNiBmpq+M1rec5MDKh/tFSKV/JOmLxbUIAxByIgTH39e+bY2El0h+vqiB12JiArahBzraYMYY+Xkty3Ysr+9o=
    - secure: clvOWlojaHQMHGhrN+sG+jOVLAsGJQFpzlUBv+8tKNy+Xbv/XPOQvnzqFTCdRlHSd39wnwIQTwOCWaCYhEECEyqgpaxYlYpSPsUOmk12aSxfjH5YGdwFqZvqhw1rkBpaEyoLh4PT0d1oLeCcJvb0jNuU4YbYOtq7DIRJDih/hPg=
matrix:
  fast_finish: true
  include:
    - env: GLTEST='build_and_install'
      python: "2.7"

    - env: GLTEST='test' GLREQUIREMENTS='trusty'
      python: "2.7"

    - env: GLTEST='lint'
      python: "2.7"

    - env: GLTEST='end2end-0' BROWSER='ie 11'
      python: "2.7"
      addons:
        sauce_connect: true

    - env: GLTEST='end2end-1' BROWSER='firefox 34'
      python: "2.7"
      addons:
        sauce_connect: true

    - env: GLTEST='end2end-2' BROWSER='firefox 45'
      python: "2.7"
      addons:
        sauce_connect: true

    - env: GLTEST='end2end-3' BROWSER='firefox beta'
      python: "2.7"
      addons:
        sauce_connect: true

    - env: GLTEST='end2end-4' BROWSER='chrome 37'
      python: "2.7"
      addons:
        sauce_connect: true

    - env: GLTEST='end2end-5' BROWSER='chrome 49'
      python: "2.7"
      addons:
        sauce_connect: true

    - env: GLTEST='end2end-6' BROWSER='chrome beta'
      python: "2.7"
      addons:
        sauce_connect: true

    - env: GLTEST='end2end-7' BROWSER='safari 8'
      python: "2.7"
      addons:
        sauce_connect: true

    - env: GLTEST='end2end-8' BROWSER='safari 9'
      python: "2.7"
      addons:
        sauce_connect: true

    - env: GLTEST='end2end-9' BROWSER='android 4.4'
      python: "2.7"
      addons:
        sauce_connect: true

    - env: GLTEST='end2end-10' BROWSER='android 5.1'
      python: "2.7"
      addons:
        sauce_connect: true

    - env: GLTEST='end2end-11' BROWSER='iphone 7.1'
      python: "2.7"
      addons:
        sauce_connect: true

    - env: GLTEST='end2end-12' BROWSER='iphone 9.2'
      python: "2.7"
      addons:
        sauce_connect: true

    - env: GLTEST='test' GLREQUIREMENTS='precise'
      python: "2.7"

    - env: GLTEST='test' GLREQUIREMENTS='xenial'
      python: "2.7"

    - env: GLTEST='test' GLREQUIREMENTS='wheezy'
      python: "2.7"

    - env: GLTEST='test' GLREQUIREMENTS='jessie'
      python: "2.7"

    - env: GLTEST='test' GLREQUIREMENTS='stretch'
      python: "2.7"

  allow_failures:
<<<<<<< HEAD
    - env: GLTEST='end2end-0' BROWSER='ie 11'
    - env: GLTEST='end2end-1' BROWSER='firefox 34'
    - env: GLTEST='end2end-2' BROWSER='firefox 45'
    - env: GLTEST='end2end-3' BROWSER='firefox beta'
    - env: GLTEST='end2end-4' BROWSER='chrome 37'
    - env: GLTEST='end2end-5' BROWSER='chrome 49'
    - env: GLTEST='end2end-6' BROWSER='chrome beta'
    - env: GLTEST='end2end-7' BROWSER='safari 8'
    - env: GLTEST='end2end-8' BROWSER='safari 9'
    - env: GLTEST='end2end-9' BROWSER='android 4.4'
    - env: GLTEST='end2end-10' BROWSER='android 5.1'
    - env: GLTEST='end2end-11' BROWSER='iphone 7.1'
    - env: GLTEST='end2end-12' BROWSER='iphone 9.2'
=======
    - env: GLTEST='end2end-1' BROWSER='ie 11'
    - env: GLTEST='end2end-2' BROWSER='firefox 34'
    - env: GLTEST='end2end-3' BROWSER='firefox 45'
    - env: GLTEST='end2end-4' BROWSER='firefox beta'
    - env: GLTEST='end2end-5' BROWSER='chrome 37'
    - env: GLTEST='end2end-6' BROWSER='chrome 48'
    - env: GLTEST='end2end-7' BROWSER='chrome beta'
    - env: GLTEST='end2end-8' BROWSER='safari 8'
    - env: GLTEST='end2end-9' BROWSER='safari 9'
    - env: GLTEST='end2end-10' BROWSER='android 4.4'
    - env: GLTEST='end2end-11' BROWSER='android 5.1'
    - env: GLTEST='end2end-12' BROWSER='iphone 7.1'
    - env: GLTEST='end2end-13' BROWSER='iphone 9.2'
>>>>>>> Deprecate IE9 and IE10; So long and thanks for all the fish!
    - env: GLTEST='test' GLREQUIREMENTS='precise'
    - env: GLTEST='test' GLREQUIREMENTS='xenial'
    - env: GLTEST='test' GLREQUIREMENTS='wheezy'
    - env: GLTEST='test' GLREQUIREMENTS='jessie'
    - env: GLTEST='test' GLREQUIREMENTS='stretch'

before_install:
  - nvm install 4.2
  - nvm use 4.2
install: true
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
script:
  - $TRAVIS_BUILD_DIR/scripts/travis.sh
