language: python
python:
  - "2.7"
before_install:
  - sudo add-apt-repository -y ppa:chris-lea/node.js
  - sudo apt-get update -qq
install:
  - sudo apt-get install tor tor-geoipdb nodejs
  - cd $TRAVIS_BUILD_DIR/backend  # to install backend dependencies
  - pip install -r requirements.txt
  - pip install coverage coveralls
  - cd $TRAVIS_BUILD_DIR/client  # to install frontend dependencies
  - npm install -g grunt grunt-cli bower
  - npm install

script:
  - cd $TRAVIS_BUILD_DIR/backend  # to run backend tests
  - coverage run setup.py test
  - coveralls || true
  - cd $TRAVIS_BUILD_DIR/client  # to run frontend tests
  - bower install && grunt build
  - $TRAVIS_BUILD_DIR/backend/bin/globaleaks -z
  - node_modules/mocha/bin/mocha -R list tests/glbackend/test_00[12356]*
