language: python
sudo: required
services:
  - docker
env:
  global:
  - secure: EVObCafLubboW7PQ69OhLI9qSMWDUYuL8EvXCX2MsBzlgX1W6cc62IJbKV87EHOnu/2KgHXYNVYN4rmydVbOU+nMHwtryf8+utNcyuDp40kKoNjWhWue++AheXgAjUt1lON4/kiZ5gxEupQeEXDPvP/5LrUuDUEQRwJa6pbivD8=
  - secure: KOpU31rbmwrjGovRX769F9H1/+KdtB5KJfMKIMRZPTeaH/zrlUDaTh9lBOkAFD1S/0nagsrXIUq9e9PJD3pEWze09VUK0mivCl96/ZXFt605UJXSKgWvZNJdRLexzwPhHd/MDzbMqTfrAlN6x9OSA5uIOaGzaQSZjkXjed8IkRk=
  - secure: MWsPYunBeYxPHk5zngCHe6K67FQc6Da9EL17vd2dLEOqePD3VPI+wVdfUDzwkdc7pslM3/JNUroMtCiVkLi7TBNH37hZ5TN1/lG/5kyqobMkm8xLInrrUOhSgvL566nRBb5QMsIMO4+yg7tQHR0EwHHjAOaI0Yw/2F2WgEZN3TU=
#Tokens order: sauce_username, sauce_token, codacy_project_token
matrix:
  fast_finish: true
  include:
    - env: GLTEST='test' DISTRIBUTION='buster' CODACY=true
      dist: bionic
      python: "3.6"
      addons:
        chrome: stable

    - env: GLTEST='build_and_install' DISTRIBUTION='buster'
      dist: bionic
      python: "3.6"

    - env: GLTEST='build_and_install' DISTRIBUTION='focal'
      dist: bionc
      python: "3.6"

    - env: GLTEST='build_and_install' DISTRIBUTION='bionic'
      dist: bionc
      python: "3.6"

    - env: GLTEST='docker'
      dist: bionic
      python: "3.6"

    - env: GLTEST='end2end-0' BROWSER='chrome 80'
      dist: bionic
      python: "3.6"
      addons:
        sauce_connect: true

    - env: GLTEST='end2end-1' BROWSER='firefox 74'
      dist: bionic
      python: "3.6"
      addons:
        sauce_connect: true

    - env: GLTEST='end2end-2' BROWSER='safari 12'
      dist: bionic
      python: "3.6"
      addons:
        sauce_connect: true

    - env: GLTEST='end2end-3' BROWSER='edge 80'
      dist: bionic
      python: "3.6"
      addons:
        sauce_connect: true

    - env: GLTEST='end2end-4' BROWSER='ie 11'
      dist: bionic
      python: "3.6"
      addons:
        sauce_connect: true

    - env: GLTEST='end2end-5' BROWSER='android 10'
      dist: bionic
      python: "3.6"
      addons:
        sauce_connect: true

    - env: GLTEST='end2end-6' BROWSER='iOS 13.2'
      dist: bionic
      python: "3.6"
      addons:
        sauce_connect: true

  allow_failures:
    - env: GLTEST='docker'
    - env: GLTEST='end2end-0' BROWSER='chrome 80'
    - env: GLTEST='end2end-1' BROWSER='firefox 74'
    - env: GLTEST='end2end-2' BROWSER='safari 12'
    - env: GLTEST='end2end-3' BROWSER='edge 80'
    - env: GLTEST='end2end-4' BROWSER='ie 11'
    - env: GLTEST='end2end-5' BROWSER='android 10'
    - env: GLTEST='end2end-6' BROWSER='iOS 13.2'
before_install:
  - nvm install stable
  - nvm use stable
install: true
script:
  - $TRAVIS_BUILD_DIR/travis/script.sh
after_success:
  - $TRAVIS_BUILD_DIR/docker/build.sh
