name: Build

on: [ push, pull_request ]

jobs:
  run_build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 1

      - name: Install git
        run: |
          sudo apt-get update -q
          sudo apt-get install -y git

      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE
          ./.github/workflows/scripts/run-build.sh
